### ISSUE TITLE
ImagePicker result doesn't return base64 image

### ISSUE THREAD

**Issue by dackom** [aaronksaunders/expo-rn-firebase-image-upload#1]
Hello, thanks for sharing this. I know that my question doesn't have anything with your code, but maybe you know answer.
My ImagePicker in expo doesn't return base64 image. I updated everything in npm to last version and my package.json versions look exactly like yours in this repo. And of course I added base64:true when requesting image. But neither camera or library photo doesn't return base64. On real device or simulator.

I see that my client version on iPhone and on simulator is 1.17.0 .... 

But there is no new expo client update in the app store.

Any ideas?

**Comment by aaronksaunders** [comment]
in your `app.json`, is your sdk version set

```
    "sdkVersion": "18.0.0",
```

**Comment by dackom** [comment]
It was in exp.json, but yes that solved problem.
Thank you.
