### ISSUE TITLE
Upload gives error on RCTNetowrking.sendrequest Object.assign

### ISSUE THREAD

**Issue by dekm** [aaronksaunders/expo-rn-firebase-image-upload#5]
When trying to upload I'm receiving this error on Object.assign.

One of the sources for assign has an enumerable key on the prototype chain. Are you trying to assign a prototype property? We don't allow it, as this is an edge case that we do not support. This error is a performance optimization and not spec compliant.

Is there a way to work around this?  I'm assuming it has to do with the base64 array for the image.

**Comment by aaronksaunders** [comment]
resolved with latest release of expo
