### ISSUE TITLE
Can currently only create Blob from other Blob

### ISSUE THREAD

**Issue by wcandillon** [aaronksaunders/expo-rn-firebase-image-upload#6]
@aaronksaunders Thank you so much for building this solution, it's really nice. However when trying I'm getting the following error:
https://www.dropbox.com/s/cz7mqropebct8wx/Screenshot%202017-12-06%2016.56.25.png?dl=0

I'm using expo 23,  RN 0.50.0, and Firebase 4.7.0.  Could that be the source of the issue? Meaning that this solution is no longer supported at the moment?

Thank you for your help.

**Comment by cometSubArc** [comment]
The same issue. Could anybody help?

    "expo": "21.0.2",
    "firebase": "^4.3.1",
    "react-native": "0.48.4",

**Comment by wcandillon** [comment]
@cometSubArc I published a workaround at https://medium.com/@wcandillon/uploading-images-to-firebase-with-expo-a913c9f8e98d

**Comment by aaronksaunders** [comment]
looks like blob support is in React-Native now and will soon make it way to expo. 

https://github.com/aaronksaunders/rn-firebase-fileupload2
